language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
matrix:
  fast_finish: true
  allow_failures:
    - node_js:
      - "0.11"
      - "0.6"
before_script:
  - npm install -g grunt-cli
script:
  - grunt
